global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'xdc_nodes'
    metrics_path: /debug/metrics/prometheus
    scheme: http
    static_configs:
      - targets: ['xdc-xinfinnetwork1-1:6060']      # container name or host:port
        labels:
          env: devnet
          service: xinfinnetwork1
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
