version: "3.7"

services:
  puppeth:
    image: xinfinorg/xdcsubnets:latest
    entrypoint: ["puppeth"]
    volumes:
      - "./puppeth:/root/.puppeth"
  subnet:
    image: xinfinorg/xdcsubnets:latest
    volumes:
      - "./xdcchain:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
    restart: "always"
    env_file: ".env"
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8555:8555"
  bootnode:
    image: xinfinorg/xdcsubnets:latest
    restart: "always"
    env_file: ".env.bootnode"
    volumes:
      - "./bootnodes:/work/bootnodes"
    entrypoint: ["bash","/work/start-bootnode.sh"]
    command: ["-verbosity", "6", "-nodekey", "bootnode.key", "--addr", ":30301"]
    ports:
      - "30301:30301/tcp"
      - "30301:30301/udp"
  stats:
    image: xinfinorg/subnet-stats-service:latest
    restart: "always"
    env_file: ".env.stats"
    volumes:
      - "./logs:/app/logs"
    ports:
      - "3000:3000"
  mainnet:
    image: xinfinorg/devnet:latest
    volumes:
      - "./xdcchain_mainnet:/work/xdcchain"
      - "./genesis.mainnet.json:/work/genesis.json"
    restart: "always"
    env_file: ".env"
    ports:
      - "30313:30303"
      - "8555:8545"
      - "8565:8555"
  relayer:
    image: xinfinorg/xdc-relayer:latest
    volumes:
      - "./xdcchain_mainnet:/work/xdcchain"
      - "./genesis.mainnet.json:/work/genesis.json"
    restart: "always"
    env_file: ".env"
